### ISSUE TITLE
Incompatible with latest Windows 11

### ISSUE THREAD

**Issue by ingrid-z** [fyr77/EnvyUpdate#26]
Unusual behavior: 
launch EvnyUpdate.exe, it's indeed shows up in tray icon then auto-crash without any information.

Windows 11 Pro 22H2
OS Build	22621.755
Windows Feature Experience Pack 1000.22636.1000.0

**Comment by fyr77** [comment]
I can reproduce this. Will fix this asap.

**Comment by fyr77** [comment]
fixed in f86025f63d1d73521837e6cb58c0a78397dd0205. 
Please download the new version 2.14 and try if that fixes the issue for you.

**Comment by fyr77** [comment]
Nvm. Found more strange API behaviour... Will work on this now.

**Comment by fyr77** [comment]
Ok, here we go. 2.15 should fix it.

The problem here was not Windows 11, but Nvidia changing their API slightly. Instead of returning a full URL to the download page as they used to, they now return on of the following:

- A full URL (rarely)
- A URL relative to the weblink
- A URL starting with `//` (Protocol-Agnostic)

If it returns anything else, an error message will now be displayed by EnvyUpdate.

**Comment by ingrid-z** [comment]
It's working now, thanks for your time and effort. 💯
