### ISSUE TITLE
App crashes when I turn on logging to file

### ISSUE THREAD

**Issue by Xaeroxe** [fyr77/EnvyUpdate#35]
I wish I could give you logs but I don't have any.

**Comment by fyr77** [comment]
Hi, is this in version 2 or 3?

**Comment by Xaeroxe** [comment]
Version 3

**Comment by fyr77** [comment]
Alright, thanks. Where is the EnvyUpdate.exe located? Do you have write permission to that folder?

**Comment by Xaeroxe** [comment]
It's in the root of my C drive which might require admin access to write. I can write there but I usually need to go through a UAC prompt.

**Comment by fyr77** [comment]
Well that explains it. I will implement a way for it to detect that and write to appdata instead. For now, please put it somewhere writeable by your user, otherwise downloading and installing drivers will also fail. I will close this issue in favour of #36, please see that issue for tracking of this topic.

**Comment by fyr77** [comment]
Added to 3.2 @Xaeroxe, fyi.
