### ISSUE TITLE
[request] embed changelog in app

### ISSUE THREAD

**Issue by jathek** [fyr77/EnvyUpdate#46]
https://github.com/ElPumpo/TinyNvidiaUpdateChecker has a nice feature where the changelog is displayed when a new driver is found. It would be nice if EnvyUpdate could show it in the app somewhere. I realize there's a link to the changelog provided, but it would be nice to have everything available at a glance in EnvyUpdate.

**Comment by fyr77** [comment]
I suppose that could be nice, but it seems somewhat redundant to me. As far as I understand this, there are a few options this could be accomplished in the GUI:

1. When there is a new version, the changelog is displayed within the main window in some text area. This is would be incredibly small in size in the worst case, making it hard to read. It could also be hidden behind a collapsible element.
2. The changelog is displayed in an extra window.

Option 1 seems not optimal to me, since it will add a lot more text to a (by default) rather small window. Option 2 seems better, but I do not quite see how it would be useful since it is very similar to just opening the browser like in the current version.

Maybe I have misunderstood something, if that is the case I would ask you kindly to clarify @jathek. Or does TNUC somehow change the format/length of the changelog to make it more readable?

**Comment by jathek** [comment]
TNUC embeds the changelog in a scrollable section like this:

https://github.com/fyr77/EnvyUpdate/assets/692914/1d15ac3b-482a-4c6a-aba5-5f91ee9d92d0

**Comment by fyr77** [comment]
While I see the potential use of this, I feel this does not really add much to the application itself. Internet is required to view the changelog no matter of where it is, and having it in a tiny window does not really make it more legible. 

I am sorry, but I do not quite see the use of this except being maybe nice, therefore I will not be working on this.

Thank you nevertheless for the suggestion and information.
