### ISSUE TITLE
Windows Defender flags 7zr.exe

### ISSUE THREAD

**Issue by DarylOrwin** [fyr77/EnvyUpdate#52]
Windows Defender is flagging and blocking 7zr.exe as PUA:Win32/Packunwan
![EnvyUpdate](https://github.com/user-attachments/assets/99c3b244-c786-45fb-b46a-9e34d7b01781)

**Comment by fyr77** [comment]
It downloads the unmodified 7zip binary from 7-zip.org (https://7-zip.org/a/7zr.exe) - it would probably be better to bundle it somehow, but that would then in turn make EnvyUpdate get flagged again... 

I have submitted the file to Microsoft as a false positive. In the meanwhile, you can try installing 7Zip or NanaZip on your machine, which should make EnvyUpdate use that instead of downloading it.

Unfortunately, I can not do much more than that, except figuring out a good way of bundling it or requiring it to be installed outright, which I would like to prevent.

**Comment by fyr77** [comment]
Hi, is this still an issue?

**Comment by DarylOrwin** [comment]
It appears to no longer be an issue.  :)
